# Generated by Django 2.0.1 on 2018-01-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catogories',
            name='test',
        ),
    ]
