# Generated by Django 2.0.1 on 2018-01-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_remove_catogories_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catogories',
            new_name='Category',
        ),
    ]
