# Generated by Django 2.0.1 on 2018-01-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='estimated_cost',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity_on_hand',
            field=models.IntegerField(default=1),
        ),
    ]
