# Generated by Django 2.0.1 on 2018-01-31 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_auto_20180130_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('preparation_time', models.IntegerField(default=1)),
                ('preparation_time_units', models.CharField(max_length=10)),
                ('cooking_time', models.IntegerField(default=1)),
                ('cooking_time_units', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Category')),
            ],
        ),
    ]
