# Generated by Django 2.0.1 on 2018-02-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_recipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipes', models.ManyToManyField(to='kitchen.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.ManyToManyField(to='kitchen.Ingredient')),
            ],
        ),
    ]
