# Generated by Django 2.0.1 on 2018-02-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_calendarentry_shoppinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarentry',
            name='date_planned',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='date_planned',
            field=models.DateField(auto_now=True),
        ),
    ]
