# Generated by Django 2.0.2 on 2018-02-02 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0009_auto_20180201_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('calendar_name', models.CharField(max_length=200)),
                ('calendar_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='calendarentry',
            name='date_planned',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='date_planned',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='calendarentry',
            name='google_calendar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kitchen.GoogleCalendar'),
            preserve_default=False,
        ),
    ]
