# Generated by Django 2.0.2 on 2018-02-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0011_recipe_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_photo',
            field=models.FileField(default='', upload_to='recipe_photos/'),
        ),
    ]
