# Generated by Django 2.0.1 on 2018-02-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0013_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id', models.IntegerField()),
                ('sheet_name', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
