# Generated by Django 2.0.1 on 2018-02-17 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0020_auto_20180217_0339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarentry',
            options={'ordering': ['-date_planned']},
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
