# Generated by Django 2.0.1 on 2018-02-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0021_auto_20180217_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='calendar_entries',
            field=models.ManyToManyField(to='kitchen.CalendarEntry'),
        ),
    ]
