# Generated by Django 2.0.1 on 2018-02-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0022_auto_20180217_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='date_planned',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='start_date',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='name',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
