# Generated by Django 2.0.1 on 2018-02-23 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0026_ingredient_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_total', models.FloatField(default=1.0)),
                ('receipt_identifier', models.CharField(max_length=100)),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kitchen.Store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreReceiptDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=100)),
                ('price', models.FloatField(default=1.0)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitchen.Store'),
        ),
        migrations.AddField(
            model_name='storereceiptdetails',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitchen.Ingredient'),
        ),
        migrations.AddField(
            model_name='storereceiptdetails',
            name='store_receipt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kitchen.StoreReceipt'),
        ),
    ]
